### ISSUE TITLE
error on load

### ISSUE THREAD

**Issue by riddik14** [benleb/ad-notifreeze#13]
2021-11-01 12:40:04.952856 WARNING notifreeze: ------------------------------------------------------------
2021-11-01 12:40:04.954232 WARNING notifreeze: Unexpected error running initialize() for notifreeze
2021-11-01 12:40:04.955583 WARNING notifreeze: ------------------------------------------------------------
2021-11-01 12:40:04.976749 WARNING notifreeze: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/app_management.py", line 163, in initialize_app
    await init()
  File "/config/appdaemon/apps/ad-notifreeze/notifreeze.py", line 176, in initialize
    since = own_messages.pop("since", self.msgs.get("since"))
AttributeError: 'str' object has no attribute 'pop'

2021-11-01 12:40:04.978141 WARNING notifreeze: ------------------------------------------------------------
2021-11-01 12:41:32.232052 WARNING notifreeze: ------------------------------------------------------------
2021-11-01 12:41:32.233346 WARNING notifreeze: Unexpected error running initialize() for notifreeze
2021-11-01 12:41:32.234421 WARNING notifreeze: ------------------------------------------------------------
2021-11-01 12:41:32.236805 WARNING notifreeze: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/app_management.py", line 163, in initialize_app
    await init()
  File "/config/appdaemon/apps/ad-notifreeze/notifreeze.py", line 176, in initialize
    since = own_messages.pop("since", self.msgs.get("since"))
AttributeError: 'str' object has no attribute 'pop'

2021-11-01 12:41:32.238747 WARNING notifreeze: ------------------------------------------------------------
2021-11-01 12:43:45.992600 WARNING notifreeze: ------------------------------------------------------------
2021-11-01 12:43:45.995026 WARNING notifreeze: Unexpected error running initialize() for notifreeze
2021-11-01 12:43:45.996732 WARNING notifreeze: ------------------------------------------------------------
2021-11-01 12:43:45.999166 WARNING notifreeze: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/app_management.py", line 163, in initialize_app
    await init()
  File "/config/appdaemon/apps/ad-notifreeze/notifreeze.py", line 176, in initialize
    since = own_messages.pop("since", self.msgs.get("since"))
AttributeError: 'str' object has no attribute 'pop'

2021-11-01 12:43:46.000660 WARNING notifreeze: ------------------------------------------------------------
2021-11-01 12:44:22.543925 WARNING notifreeze: ------------------------------------------------------------
2021-11-01 12:44:22.546171 WARNING notifreeze: Unexpected error running initialize() for notifreeze
2021-11-01 12:44:22.548099 WARNING notifreeze: ------------------------------------------------------------
2021-11-01 12:44:22.561108 WARNING notifreeze: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/app_management.py", line 163, in initialize_app
    await init()
  File "/config/appdaemon/apps/ad-notifreeze/notifreeze.py", line 176, in initialize
    since = own_messages.pop("since", self.msgs.get("since"))
AttributeError: 'str' object has no attribute 'pop'

2021-11-01 12:44:22.562737 WARNING notifreeze: ------------------------------------------------------------

my conf

notifreeze:
  module: notifreeze
  class: NotiFreeze
  messages: en_US
  #messages: "ciao c'è una finestra aperta"
  notify_service: notify.telegram #script.notify
  always_notify: false
  outdoor: sensor.temperatura_esternna
  max_difference: 2.2
  delays:
    initial: 3
    reminder: 7
  rooms:
    - Schlafzimmer
    - Bad
    - name: Wohnzimmer
      alias: livingroom  # entity ids contain *livingroom* but not *wohnzimmer*
    - name: Keller
      door_window: binary_sensor.finestra_salone
      indoor:
        - sensor.temperature_media_interna

**Comment by clipse2004** [comment]
Hey, your config is wrong 

messages:
    since: "{room_name} {entity_name} offen 
                seit {open_since}: {initial}°C"
    change: "{room_name} {entity_name} offen
                   seit {open_since}: {initial}°C → 
                   {indoor}°C ({indoor_difference}°C)"

sorry cannot convert it better :/
