### ISSUE TITLE
error with "messages"

### ISSUE THREAD

**Issue by bluenazgul** [benleb/ad-notifreeze#14]
Log within AppDaemon4

```
2021-12-08 09:46:10.706731 WARNING notifreeze: ------------------------------------------------------------
2021-12-08 09:46:10.706559 WARNING notifreeze: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/app_management.py", line 163, in initialize_app
    await init()
  File "/config/appdaemon/apps/ad-notifreeze/notifreeze.py", line 176, in initialize
    if own_messages := self.args.pop("messages"):
KeyError: 'messages'

2021-12-08 09:46:10.706178 WARNING notifreeze: ------------------------------------------------------------
2021-12-08 09:46:10.705960 WARNING notifreeze: Unexpected error running initialize() for notifreeze
2021-12-08 09:46:10.705743 WARNING notifreeze: ------------------------------------------------------------
```

my config:
```
notifreeze:
  module: notifreeze
  class: NotiFreeze
  locale: de_DE
  notify_service: notify.notify
  always_notify: false
  outdoor: sensor.lumi_lumi_weather_temperature
  max_difference: 4.2
  delays:
    initial: 3
    reminder: 7
  rooms:
    - name: Kinderzimmer
      door_window: binary_sensor.lumi_lumi_sensor_magnet_aq2_eafbc306_on_off
      indoor: sensor.lumi_lumi_weather_d2387507_temperature
    - name: Wohnzimmer
      #alias: livingroom  # entity ids contain *livingroom* but not *wohnzimmer*
      door_window: binary_sensor.lumi_lumi_sensor_magnet_aq2_8aede406_on_off
      indoor:
        - sensor.fritz_dect_rep_100_oben
        - sensor.lumi_lumi_weather_07381107_temperature
```

**Comment by costasfait** [comment]
hi, did you got the solution for this?
i have the same issue!!

**Comment by mcmasterp** [comment]
any resolution?
